import streamlit as st


def project_hypothesis_page_body():
    st.write("## Project Hypotheses and Validation")

    st.success(
        "🔍**First Hypothesis : The Relationship Between Property Size "
        "and Sale Price**\n\n"
        "Our initial hypothesis posits that larger properties tend to "
        "command higher absolute sale prices. This assumption is based "
        "on the general principle that more spacious properties offer "
        "greater utility, which can be an attractive factor for "
        "potential buyers.\n\n"
        "* ✅**Hypothesis Confirmation:** After conducting a thorough "
        "correlation analysis, we observed a positive and moderate "
        "correlation between property size-related features and sale "
        "price. This suggests that, as expected, larger homes tend to "
        "sell for higher prices, reinforcing our initial assumption.\n\n"
        "🔍**Second Hypothesis: The Impact of Overall Quality on Sale "
        "Price**\n\n"
        "We hypothesize that the overall quality of a house plays a "
        "significant role in determining its sale price. Properties "
        "with higher quality ratings—indicative of superior materials, "
        "craftsmanship, and overall design—are expected to fetch "
        "higher market values due to increased buyer preference and "
        "perceived long-term value.\n\n"
        "* ✅**Hypothesis Confirmation:** Our analysis confirms a strong "
        "correlation between a property's overall quality rating and "
        "its sale price. The data suggests that higher quality homes "
        "consistently achieve higher market valuations, supporting our "
        "hypothesis that construction quality is a key factor in "
        "pricing dynamics.\n\n"
        "🔍**Third Hypothesis: The Influence of Property Condition on "
        "Market Value**\n\n"
        "We further hypothesize that a property's overall condition "
        "will significantly impact its sale price. Well-maintained "
        "homes, particularly those with recent renovations or newer "
        "construction dates, are expected to be more desirable to "
        "buyers and, as a result, command higher sale prices.\n\n"
        "* ✅**Hypothesis Confirmation:** The findings of our correlation "
        "analysis support this hypothesis. Specifically, we identified "
        "a positive and moderate correlation between sale price and "
        "factors such as the property's construction year and last "
        "recorded remodel year. These results indicate that newer and "
        "recently updated homes tend to sell at higher prices, "
        "affirming the importance of property condition in market "
        "valuation.\n\n"
    )
